server:
    port: 8082
spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchenge:
        producer: ex.producer.classone.spring
      routing-key:
        producer: rk.producer.classone.spring
     # deadletter:
     #   producer: rk.producer.classone.spring